### ISSUE TITLE
Tests for ShowPretty fail on Windows

### ISSUE THREAD

**Issue by Michaelt293** [typelevel/kittens#158]
Currently, newlines are hardcoded to `\n` in `ShowPretty`. This results in the tests for `ShowPretty` failing on Windows. The tests pass on Windows if `sys.props("line.separator")` is used instead.

Is this a good approach to solve this issue?

**Comment by joroKr21** [comment]
Good catch! I think we should use `System.lineSeparator`.

**Comment by Michaelt293** [comment]
@joroKr21 Raised a PR - https://github.com/typelevel/kittens/pull/159. Agree that `System.lineSeparator` is the better choice.

**Comment by joroKr21** [comment]
Fixed in #159
