### ISSUE TITLE
Unable to derive Foldable.

### ISSUE THREAD

**Issue by Josef-Vonasek** [typelevel/kittens#196]
The following code:
```scala
final case class Foo[T](a: Seq[T], b: Option[T])
implicit def fold: Foldable[Foo] = semi.foldable
```
results in error `required MkFoldable[Foo], got MkFoldable[shapeless.Id]`.
Note that deriving functor with `semi.functor` works just fine.

**Comment by joroKr21** [comment]
Hi, would you mind sharing the definition of `Foo`?
Also you might want to try `semi.foldable[Foo]` (to make sure it's not a type inference issue)
And btw it's better to ask questions on the gitter channel: https://gitter.im/typelevel/kittens

**Comment by Josef-Vonasek** [comment]
I have added the definition.

**Comment by joroKr21** [comment]
Do you have a `Foldable[Seq]` in scope? I'm suprised even `Functor[Seq]` would work.

**Comment by Josef-Vonasek** [comment]
Alright, I have replaced the definition:
```scala
import cats.implicits._
final case class Foo[T](s: String, l: List[T], o: Option[T])
```
But I am still getting the same error.

**Comment by joroKr21** [comment]
Hmm can you share a bit more? It works for me.
Which version of Scala / Kittens are you using?

**Comment by Josef-Vonasek** [comment]
Scala 2.12.8, kittens 1.2.1

**Comment by joroKr21** [comment]
Sorry I may not be on my computer until tomorrow.
You could try with `-Ypartial-unification` or with Scala 2.12.10

**Comment by Josef-Vonasek** [comment]
Partial unification did not help, but updating scala did! Thank you.
