### ISSUE TITLE
It doesn't work on AWS Lambda. Runtime : Java8 / Java11

### ISSUE THREAD

**Issue by barisAtmn** [typelevel/kittens#264]

**Comment by joroKr21** [comment]
Hi @barisAtmn what error are getting specifically? Do you mean Coretto JDK?
Without instructions how to reproduce the problem it's unlikely that anyone would be able to help.

**Comment by joroKr21** [comment]
The tests work both on Java `8.0.275-amzn` and `11.0.9-amzn`

**Comment by joroKr21** [comment]
Reopen if you have more information
