### ISSUE TITLE
Port for Scala 3

### ISSUE THREAD

**Issue by joroKr21** [typelevel/kittens#282]
I'm not sure if we should wait for Shapeless 2 to cross compile.
Maybe it's better to start from scratch with Shapeless 3.

**Comment by catostrophe** [comment]
@joroKr21 should his one be closed?

**Comment by catostrophe** [comment]
Oh, you haven't released it. Sorry

**Comment by joroKr21** [comment]
It's a work in progress on the `dotty` branch

**Comment by gvolpe** [comment]
@joroKr21 any plans to publish a snapshot of the `dotty` branch at least? I'd be keen to use it already :)

**Comment by joroKr21** [comment]
@gvolpe great idea 👍 will do as soon as I find some time

**Comment by gvolpe** [comment]
Thanks @joroKr21, this is exciting stuff!

**Comment by joroKr21** [comment]
Published 3.0.0-M1

**Comment by akreuzer** [comment]
> Yeah indeed - still need to figure out how to include js in the build. I think we can publish M2 once we have that.

I think you just have to add `coreJS` to this line. https://github.com/typelevel/kittens/blob/873ae0d9ef43e11884606391d34c63b3794f5d97/build.sbt#L69-L74

Thank you for the great work!

**Comment by joroKr21** [comment]
Sorry for the delay - I released [v3.0.0-M3](https://github.com/typelevel/kittens/tree/v3.0.0-M3) with Scala.js support. Thanks to @armanbilge `sbt-typelevel` handles this stuff for us. We can also support Scala Native soon (but we need a Shapeless 3 release first).

**Comment by gvolpe** [comment]
@joroKr21 you're probably aware but if not, know that both M2 and M3 stopped working with simple derivations of `Eq`, `Show`, etc, so I'm staying on M1 for the time being. More details: https://github.com/gvolpe/trading/runs/5177513241?check_suite_focus=true

**Comment by joroKr21** [comment]
@gvolpe you just need to `import cats.derived.*`

**Comment by joroKr21** [comment]
This causes a compiler crash for me 😞 
```scala
sealed trait AlertType derives Show:
  case object StrongBuy extends AlertType
```

**Comment by joroKr21** [comment]
@gvolpe looks like this works:
```scala
sealed trait AlertType derives Show
object AlertType:
  case object StrongBuy extends AlertType
```

But the enum doesn't. I'm not sure what's the difference. But we don't have tests for enums yet.

**Comment by joroKr21** [comment]
This also works:
```scala
enum AlertType derives Show:
  case StrongBuy()
```

**Comment by gvolpe** [comment]
Thanks for looking! So it looks like an issue then. Here's another case that works as well:

```scala
import cats.Show
import cats.derived.*
import io.circe.Codec

enum TradeAction derives Codec.AsObject, Show:
  case Ask, Bid
```

**Comment by joroKr21** [comment]
> For the record, this works in M1: https://scastie.scala-lang.org/obUaNiH9TDSWvBy7mz546A

It doesn't for me

**Comment by gvolpe** [comment]
> It doesn't for me

What do you mean? That's actually compiling on Scastie using the first milestone 😄

**Comment by joroKr21** [comment]
Ah you mean Kittens 3.0 M1 - For some reason I thought of Apple M1.
Yeah there seems to be some issue with the current scheme or with Dotty itself.
We will have to investigate. But it only manifests for enum singletons (which are **not** objects I think).

**Comment by gvolpe** [comment]
Ah yeah, sorry, I do not use Mac 😄 

Do you want me to raise a separate issue to track the enum's issue? No rush anyway, should be expected in milestones :)

**Comment by joroKr21** [comment]
> Do you want me to raise a separate issue to track the enum's issue?

Yes please, that sounds good 👍

**Comment by TimWSpence** [comment]
I just created https://github.com/typelevel/kittens/issues/481 to track the outstanding issues blocking a full scala 3 release. Feel free to add to it if I've missed any!

**Comment by joroKr21** [comment]
More details in #481
