### ISSUE TITLE
ShowPretty for Map[K, V]

### ISSUE THREAD

**Issue by Lasering** [typelevel/kittens#301]
It seems kittens does not derive showPretty for Map[K, V]

https://scastie.scala-lang.org/z8h9qwfrSXu2xIwARJ6ndg

```scala
import cats.Show._
import cats.derived
import cats.derived.ShowPretty
import cats.derived.auto.show._

derived.semiauto.showPretty[Map[String, String]]
```

```
Could not derive an instance of ShowPretty[A] where A = Map[String,String].
Make sure that A satisfies one of the following conditions:
  * it is a case class where all fields have a Show instance
  * it is a sealed trait where all subclasses have a Show instance
```

**Comment by joroKr21** [comment]
We don't have any `ShowPretty` instances for the standard library. What is your use case? I think it only makes sense for ADTs and `ShowPretty extends Show` so you can just use `Show` in your own code and derive `ShowPretty` as needed.

**Comment by joroKr21** [comment]
Perhaps we could define instances for `Map` and `Iterable`
