### ISSUE TITLE
[Scala 3] - Wildcard derivation import not working

### ISSUE THREAD

**Issue by gvolpe** [typelevel/kittens#425]
Super simple reproduction:

```scala
import cats.Show
// import cats.derived.semiauto.{ derived, product } // this works
// import cats.derived.semiauto.{ given, * } // this works (as per the 3rd comment)
import cats.derived.semiauto.* // does not work

enum TradeAction derives Show:
  case Ask, Bid
```

It fails with the following error:

```
no implicit argument of type cats.Show[(Playground.TradeAction.Ask : Playground.TradeAction)] was found

The following import might fix the problem:

  import cats.derived.semiauto.product
```

https://scastie.scala-lang.org/0q4XaUbJTqibfe78MuyzAA

---

Not sure whether this has already been discussed or not but I figured it might be better to keep track of it right here.

**Comment by gvolpe** [comment]
Another example that adds `Eq`:

```scala
import cats.{ Eq, Show }
// import cats.derived.semiauto.{ derived, product, productOrder } // this works
import cats.derived.semiauto.* // does not work

enum ForecastTag derives Eq, Show:
  case Long, Short
```

Fails with the following error:

```
no implicit argument of type cats.kernel.Eq[(Playground.ForecastTag.Long : Playground.ForecastTag)] was found

The following import might fix the problem:

  import cats.derived.semiauto.productEq

no implicit argument of type cats.Show[(Playground.ForecastTag.Long : Playground.ForecastTag)] was found
```

https://scastie.scala-lang.org/HGVuAPc3TlmfGyirNlYVxw

**Comment by gvolpe** [comment]
There are a few other (probably related) issues with `sealed trait` as well, if it's useful, I can try to produce a minimal reproducible example of this: https://github.com/gvolpe/trading/blob/main/modules/domain/src/main/scala/trading/commands/ForecastCommand.scala#L8

**Comment by gvolpe** [comment]
Ok, I rushed into this, the first two are simply fixed with this import

```scala
import cats.derived.semiauto.{ given, * }
```

The latter still does not work but I will create a proper issue with a repro.

**Comment by gvolpe** [comment]
Hmmm this for some reason does not compile locally:

```scala
import cats.{ Eq, Show }
import cats.derived.semiauto.{ given, * } 
import cats.syntax.all.*

enum TradingStatus derives Eq, Show:
  case On, Off

object TradingStatus:
  def from(str: String): Option[TradingStatus] =
    Either.catchNonFatal(valueOf(str)).toOption
```

But it compiles just fine on Scastie: https://scastie.scala-lang.org/7Eqo9m1hRNCdhX55GTTBdw

I need to dig in more into this.

**Comment by joroKr21** [comment]
Kittens for Scala 3 is not ready yet - I think some functionality is missing / not implemented in the released version.
But we are blocked by a Scala compiler issue: lampepfl/dotty#13406
On the other hand we need a newer version that contains this fix: lampepfl/dotty#14003

**Comment by gvolpe** [comment]
Thanks for the quick reply, @joroKr21 ! 

I understand it's not ready yet. Are you keeping track of the issues / limitations somewhere else? If not, it's probably a good idea to have them on this repo, no?

**Comment by joroKr21** [comment]
> I understand it's not ready yet. Are you keeping track of the issues / limitations somewhere else? If not, it's probably a good idea to have them on this repo, no?

Yeah, I'm just not sure if this is a limitation that applies in general or we just need to get unblocked by fixing that Scala bug and release 😄

**Comment by gvolpe** [comment]
Got you! Ok, if you don't mind, I'll leave this issue open but will refrain from opening new ones. I was aware of these issues for a while but I thought I should raise it here now that the project where I use Kittens is public 😄

**Comment by TimWSpence** [comment]
Thanks @gvolpe! It's great to have feedback on what else we might need to fix once we're unblocked upstream 😅

**Comment by joroKr21** [comment]
Let's just go for it and release what we can - even if it's not working perfectly at least people can use it.
#427 is the first step. We still have a around half the type classes to port.

**Comment by gvolpe** [comment]
That is awesome, thanks @joroKr21 🤩
