### ISSUE TITLE
Support enum derivations

### ISSUE THREAD

**Issue by gvolpe** [typelevel/kittens#449]
Using the latest milestone M3, this `Show` derivation fails to compile.

```scala
import cats.Show
import cats.derived.*
import cats.syntax.all.*

enum AlertType derives Show:
  case StrongBuy, StrongSell, Neutral, Buy, Sell
```

Scastie for M3: https://scastie.scala-lang.org/ipl7t5TmTwiU7fRzO6b0uw

---

In the first publish milestone M1, it works when having the right imports (`import cats.derived.semiauto.*` doesn't work).

```scala
import cats.Show
import cats.derived.semiauto.{ derived, product }
import cats.syntax.all.*

enum AlertType derives Show:
  case StrongBuy, StrongSell, Neutral, Buy, Sell
```

Scastie for M1: https://scastie.scala-lang.org/AExX3biyTCW0f9cpzyCYRw

It seems enum singletons are not objects but it requires a bit more of investigation.

**Comment by andrzejressel** [comment]
I guess another weird behaviour like with Tuples. We should see if there are any commits in Dotty/shapeless related to enums.

**Comment by andrzejressel** [comment]
I guess we found another weird case apart from recursive types: enums

**Comment by andrzejressel** [comment]
Changing
```
using inst: => K0.CoproductInstances[Or, A]
```
to
```
using inst: K0.CoproductInstances[Or, A]
```
Seems to fix the issue. I guess there is something wrong with Shapeless.

**Comment by andrzejressel** [comment]
I've prepare minimal'ish example: https://scastie.scala-lang.org/andrzejressel/fuqm27fSSgyTxDlAulJCkw/7

And I've found even more weird behaviour: you can comment out product - it compiles fine ...

**Comment by joroKr21** [comment]
Fixed upstream (coming soon in Scala 3.1.3)

**Comment by gvolpe** [comment]
Awesome! @joroKr21 will the current milestone work with Scala 3.1.3? Or this requires publishing a new milestone against this new Scala version? If so, please ping me when there's a new tag release, so I can try it out 🙏🏽

**Comment by joroKr21** [comment]
I don't know if it requires a new milestone but I pushed `v3.0.0-M4` anyway because we have extended the support for more type classes since.

**Comment by gvolpe** [comment]
Thank you! 🚀
