### ISSUE TITLE
[Scala 3] Missing derivations

### ISSUE THREAD

**Issue by TimWSpence** [typelevel/kittens#483]
Currently the delta between scala 2 and scala 3 typeclass derivation is:
```
ShowPretty
ConsK
Iterable
```

I assume that we want to implement these as well?

**Comment by joroKr21** [comment]
* `ShowPretty` - I think that's the most useful of the three 👍 
* `ConsK` - I don't know about that one, it would require some research - we can always add it later
* `Iterable` - not really a type class and what does it offer on top of `Foldable` - maybe we can cut it

**Comment by TimWSpence** [comment]
Yeah I was surprised that we derive `Iterable` - very happy to drop it 👍
