### ISSUE TITLE
`Monoid` derivation applies requires `Monoid` for type parameter even when unnecessary

### ISSUE THREAD

**Issue by mrdziuban** [typelevel/kittens#546]
At least on scala 3 (haven't tested on scala 2) a derived `Monoid[F[A]]` requires a `Monoid[A]` even if `A` is only referenced within types that have a `MonoidK` instance, i.e. that can form a `Monoid` regardless of their type parameter.

Could it instead require any number of `Monoid[B]`s where `B` is the full type of the each field that references `A`? For example:

```scala
case class Test[A](l: List[A], v: Vector[A]) derives Monoid

// generated before
given derived$Monoid[A](using m: Monoid[A]): Monoid[Test[A]]
// generated after
given derived$Monoid[A](using m1: Monoid[List[A]], m2: Monoid[Vector[A]]): Monoid[Test[A]]
```

Full example:

https://scastie.scala-lang.org/mrdziuban/wy1ITtp9SCCyUe7uUgfisA/4

```scala
import cats.Monoid
import cats.derived.*

case class Test[A](l: List[A]) derives Monoid

Monoid[Test[Boolean]]
/*
No given instance of type cats.kernel.Monoid[Playground.Test[Boolean]] was found for parameter ev of method apply in object Monoid.
I found:

    Playground.Test.derived$Monoid[Boolean](
      /* missing */summon[cats.kernel.Monoid[Boolean]]
    )

But no implicit values were found that match type cats.kernel.Monoid[Boolean].

One of the following imports might fix the problem:

  import cats.derived.auto.commutativeMonoid.given_CommutativeMonoid_A
  import cats.derived.auto.monoid.given_Monoid_A
*/
```

**Comment by joroKr21** [comment]
Yeah I think that comes from Scala 3 and we can't control it 😞

**Comment by joroKr21** [comment]
The workaround is to add the instance to the companion object explicitly:
```scala
object Test:
  given [A] Monoid[Test[A]] = semiauto.monoid

**Comment by mrdziuban** [comment]
Oooh interesting and good to know! Feel free to close this then since it's not a kittens issue

**Comment by joroKr21** [comment]
Maybe we should document this in the README so I will keep it open.

**Comment by benhutchison** [comment]
FWIW I hit this same issue today. I guess I shoulda read the docs.

I have a case class `Section[K: Ordering, V: Monoid](entries: SortedMap[K, V])`. Since a Map has a monoid instance that merges keys, we don't need to monoidally combine the `K`, but the derivation failed looking for `Monoid[K]`. Oh well, I wrote it full manually but I'll play around with semi-auto derivation when I get time.
