### ISSUE TITLE
Type argument does not have the same kind as its bound 

### ISSUE THREAD

**Issue by avanov** [typelevel/kittens#547]
Hi!

Am I missing something obvious here (Scala 3.2.1)?

```scala
import cats.derived.*
import cats.derived.semiauto
import cats.{Show, Eq, Functor}
import cats.data.EitherT
import cats.effect.IO

opaque type Parser[A] = EitherT[IO, String, A]
given [A: Functor] : Functor[Parser[A]] = semiauto.functor
```

produces
```
[error] 12 |given [A: Functor] : Functor[Parser[A]] = semiauto.functor
[error]    |                 ^
[error]    |          Type argument A does not have the same kind as its bound [_$1]
[...]
[error] 12 |given [A: Functor] : Functor[Parser[A]] = semiauto.functor
[error]    |                             ^^^^^^^^^
[error]    |Type argument pkg.Pkg$package.Parser[A] does not have the same kind as its bound [_$1]
```

**Comment by joroKr21** [comment]
I don't think you need kittens for opaque types. As long as you're in scope of its definition, you should be able to summon the instance from implicit scope if it exists. What you're missing here is that `Functor` takes a type constructor `F[_]` so `Functor[F[_]]` but here you're passing `A` which is doesn't take any type arguments. You shouldn't really need any bound on `A` to have a `Functor` instance.

**Comment by avanov** [comment]
Indeed, you're right about summoning. Closing this, as I misidentified the cause of the issue.
