### ISSUE TITLE
[Scala 2] Instances for Records and Unions

### ISSUE THREAD

**Issue by joroKr21** [typelevel/kittens#60]
Kittens allows us to work with raw HLists and Coproducts:
```scala
import cats.instances.all._
import cats.derived.MkMonoid._
import cats.syntax.monoid._

1 :: "a" :: HNil |+| 2 :: "b" ::HNil // ok
```
However, we can't work with raw Records and Unions:
```scala
'k ->> 1 :: HNil |+| 'k ->> 2 :: HNil // no Monoid instance
```
The same goes for other type classes as well. It mostly boils down to defining an instance for `FieldType[K, V]`. Are there any objections to adding them?

**Comment by kailuowang** [comment]
:+1: from me.

**Comment by joroKr21** [comment]
I'm having some trouble with HKTs. For some reason:
```scala
implicit def mkFunctorFieldType[K, V[_]: Functor]: Functor[λ[t => FieldType[K, V[t]]]] =
  new Functor[λ[t => FieldType[K, V[t]]]] {
    def map[A, B](fa: FieldType[K, V[A]])(f: A => B) =
      field[K](Functor[V].map(fa)(f))
  }

type F[x] = FieldType['a, Vector[x]] :: HNil
type G[x] = FieldType['b, Vector[x]] :+: CNil
MkFunctor[F] // ok
MkFunctor[G] // missing
```
I'm at a loss why there would be any difference between the two.

**Comment by kailuowang** [comment]
This is indeed puzzling. Implicit log didn't give you any clue? Removing the lazy might help debugging?

**Comment by joroKr21** [comment]
I'm quite sure these mostly work now (or they will after #134 is complete).
So it's a matter of adding tests to close this issue.
