### ISSUE TITLE
Performance Regression

### ISSUE THREAD

**Issue by fosskers** [typelevel/kittens#88]
When updating version numbers for [scalaz-and-cats](https://github.com/fosskers/scalaz-and-cats) I noticed a fairly stark performance regression for kittens-derived `Eq` between RC1 and RC3.

For a simple case-class:
```scala
case class Foo(age: Int, msg: String, truthy: Boolean)
```
Previously the deriving syntax was:
```scala
implicit val fooEq: Eq[Foo] = derive.eq[Foo]
```
And now it is:
```scala
    implicit val fooEq: Eq[Foo] = {
      import derived.auto.eq._
      derived.semi.eq
    }
```
For two length-10000 `List[Foo]` who have the same contents but are not the same object, to compare every element dropped from **38,630 ns** to **45,416 ns**. Either number is an order of magnitude slower than a hand-written instance, vanilla Scala's `==`, or a ScalaZ auto-derived instance.

**Comment by kailuowang** [comment]
When we introduced `OrElse` we knew there was a performance penalty, but the benefit is to support using existing instances for fields with them. This is important because kittens allows you to derive instances for classes whose source you can't or don't want to change.  Being able to automatically reuse existing instances for certain types are important.  

BTW, for your simple case classes a simple 
```scala 
implicit val fooEq: Eq[Foo] = derived.semi.eq[Foo]
```
works just fine, or a single line `import derived.auto.eq._`
You only need to use the more verbose way if your `Foo` has fields that do come up native `Eq` instances and you don't want to manually write `implicit val barEq: Eq[Bar] = derived.semi.eq[Bar]` for each of them.

**Comment by fosskers** [comment]
Oh cool, I didn't realize the syntax could be simplified. I'll change it back.

Regardless of Vanilla Scala or ScalaZ, the fact remains that the kittens auto-gen'd instances are an order of magnitude slower than hand-written instances. How should this be approached? Is there a way to see what the generated code is? Forgive me for not knowing if this is macro-based or reflection or something.

**Comment by kailuowang** [comment]
It's shapeless based,  so under the hook it's probably using `Product`'s `productElement` obviously with some overhead.  @milessabin might be able to point out some optimization that can be done?

**Comment by milessabin** [comment]
shapeless doesn't use `Product` or `productElement` ... `Generic` maps directly between case classes and an `HList` representation.

There have been no significant changes in shapeless in this respect recently, so if you're seeing a slowdown between kittens RCs then I think it must be down to changes in kittens.

On the delta with handwritten code or a direct macro-based solution, that's most likely a direct consequence of going through a generic representation type.

**Comment by fosskers** [comment]
Hey guys, just a reminder that this regression is still present in the new `1.0.0` release.

**Comment by joroKr21** [comment]
There is tension between the desire for performance and for full generality (including support for custom instances and recursive data types). If we could fully instantiate the comparing function at the time of returning the `Eq` instance we could at least avoid the access of lazy vals. Is there a way to achieve that?

**Comment by joroKr21** [comment]
We should check how it looks like on Scala 2.13

**Comment by joroKr21** [comment]
@fosskers did you close this issue because it's stale or it has progressed?

**Comment by fosskers** [comment]
Stale, I assume it's not relevant anymore.
