### ISSUE TITLE
Improve @implicitNotFound error messages

### ISSUE THREAD

**Issue by ykycxzsv** [typelevel/kittens#89]
I copied the code from documentation and replaced Show with Eq:
```
import cats._

case class A(a: Int)

object Test {
  implicit val eq: Eq[A] = {
    import derived.auto.eq._
    derived.semi.eq
  }
}
```
Compiled with Scala 2.12.4 (https://scastie.scala-lang.org/z4Ksxl4lR26ECCDjmGSAxQ)
```
Adaptation of argument list by inserting () is deprecated: this is unlikely to be what you want.
        signature: OrElse.primary[A, B](implicit a: A): shapeless.OrElse[A,B]
  given arguments: 
 after adaptation: OrElse.primary((): Unit)

ambiguous implicit values:
 both value mkEqHnil in class MkEqDerivation of type => cats.derived.MkEq[shapeless.HNil]
 and value mkEqCnil in class MkEqDerivation of type => cats.derived.MkEq[shapeless.CNil]
 match expected type cats.derived.MkEq[A]

could not find implicit value for parameter ev: cats.derived.MkEq[A]

not enough arguments for method eq: (implicit ev: cats.derived.MkEq[A])cats.Eq[A].
Unspecified value parameter ev.
```

**Comment by kailuowang** [comment]
Need to import cats.implicits._ to get the Eq instance for Int. That would fix this. 
We might be able to improve the puzzling error message. (I am on my phone, will check it out later)

**Comment by ykycxzsv** [comment]
Thanks, that did the trick. I'll leave the issue open if you want to use it for improving the error message. In particular, the "Adaptation of argument list by inserting ()" part is very confusing

**Comment by joroKr21** [comment]
I am adding error messages as part of #134 
Currently:
> Could not derive an instance of Eq[A]

Should we try to explain more? If so how much?

**Comment by kailuowang** [comment]
I think we can mention that kittens relies on instances for field types to drive instance for classes.
